### ISSUE TITLE
Data source not found error.

### ISSUE THREAD

**Issue by sankerust** [CorpGlory/grafana-data-exporter-panel#28]
When opening the dashboard with the exporter this error arises:
![image](https://user-images.githubusercontent.com/22073083/46496638-33014f80-c821-11e8-8957-444102ccb4c3.png)

Steps to reproduce:
- Have grafana-data-exporter running
- Open dashboard with grafana-data-exporter panel and simpleJson panel in it.

As soon as the dashboard is opened, exporter server crashes with this error:
![image](https://user-images.githubusercontent.com/22073083/46496923-e36f5380-c821-11e8-8f88-f0929d756109.png)

Chrome console:
![image](https://user-images.githubusercontent.com/22073083/46497277-cab36d80-c822-11e8-8501-81b56c3d2bce.png)

Network tab looks like this:
![image](https://user-images.githubusercontent.com/22073083/46496978-fa15aa80-c821-11e8-9897-eee9cc4ba43b.png)

**Comment by rozetko** [comment]
fixed
