### ISSUE TITLE
Cannot find datasource id in url api/tsdb/query

### ISSUE THREAD

**Issue by versatildefuy** [CorpGlory/grafana-data-exporter-panel#32]
Hello guys,

I tried to set up your plugin following the [getting started guide](https://github.com/CorpGlory/grafana-data-exporter-panel/wiki), but after installing it Grafana returns an error for PostgreSQL datasource.

![image](https://user-images.githubusercontent.com/16953641/70991560-fd642180-20c7-11ea-8af3-cd4cb67a9a21.png)

I set up and started Grafana for local development as explained [here](https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md) and I followed all the steps in the installation guide.

> Installation
>     grafana-data-exporter for fetching data from Grafana datasources.
>     simple-json-datasource for progress tracking.
>     grafana-data-exporter-panel for exporting metrics from dashboard.
>     Import exporting template dashboard at http://<YOUR_GRAFANA_URL>/dashboard/import

What am I doing wrong? Should I use a specific version of Grafana?

Thank you in advance :)

**Comment by rozetko** [comment]
Hi @versatildefuy,

Thanks for the bug report. It's a general issue with SQL datasources support: https://github.com/CorpGlory/grafana-data-exporter-panel/issues/33. So PostgreSQL is not supported at this moment.

**Comment by jonyrock-back** [comment]
@versatildefuy we can fix it in one mouth. If you want to see it faster, please ping us: ping@corpglory.com

**Comment by versatildefuy** [comment]
Ok guys, thank you. I think this is a promising plugin. I am looking forward to using it :)

**Comment by rozetko** [comment]
@versatildefuy we've fixed it in the latest 0.3.6 release:
https://github.com/CorpGlory/grafana-data-exporter-panel/releases/tag/0.3.6

**Comment by versatildefuy** [comment]
Thank you very much @rozetko . I will try the new version during the next days and I will provide feedback.
