### ISSUE TITLE
MySQL / PostgreSQL support

### ISSUE THREAD

**Issue by rozetko** [CorpGlory/grafana-data-exporter-panel#33]
There is a "Cannot find datasource id in url api/tsdb/query" when a SQL datasource is used.

`grafana-data-exporter-panel` expects the datasource to have `/api/datasources/:id` proxy URL. SQL datasources' "Proxy URL" differs from other datasources: it has `/api/tsdb` proxy URL. 
We should support this case.

**Comment by anirudh-ramesh** [comment]
When used with an SQL database, this panel irreversibly changes the proxy URL to `/api/datasources/:id` and the only way to recover would be to delete the organization and restart.
