### ISSUE TITLE
Add scrteenshots to the repo

### ISSUE THREAD

**Issue by jonyrock** [CorpGlory/grafana-data-exporter-panel#38]
We have nice graphic on https://corpglory.com/s/grafana-data-exporter/ , but we don't have anything in the README.md

**Comment by rozetko** [comment]
closed in https://github.com/CorpGlory/grafana-data-exporter-panel/commit/9cf2d9a4c620674f24ec2ba00b8755c421e345ee

**Comment by mattchaley** [comment]
@jonyrock GIF added + small text fix 
https://github.com/CorpGlory/grafana-data-exporter-panel/blob/master/README.md
