### ISSUE TITLE
Missing default datasource 

### ISSUE THREAD

**Issue by jonyrock** [CorpGlory/grafana-data-exporter-panel#39]
Steps to reproduce: create a panel with prometheus query which selected as "default", like this:
![image](https://user-images.githubusercontent.com/1022757/87880287-dcaed200-c9f0-11ea-82d7-cf234d233346.png)

and I will not appear in the grafana-data-exporter-panel list...

**Comment by corpglory-dev** [comment]
Might be related: https://github.com/hastic/hastic-grafana-app/pull/257
