### ISSUE TITLE
Grafana 7: Exporter panel doesn't see datasource

### ISSUE THREAD

**Issue by corpglory-dev** [CorpGlory/grafana-data-exporter-panel#40]
Grafana version: 7.0.3

grafana-data-exporter-panel version: latest master (https://github.com/CorpGlory/grafana-data-exporter-panel/commit/9cf2d9a4c620674f24ec2ba00b8755c421e345ee)

Steps to reproduce:
- import [dashboard template](https://raw.githubusercontent.com/CorpGlory/grafana-data-exporter-panel/master/examples/dashboard.json)
- add query to `Data` panel
- save and refresh the dashboard

Expected behaviour:
- expected to see `prometheus` datasource from `Data` panel in `Exporter` panel

Actual behaviour:
![image](https://user-images.githubusercontent.com/47055832/88178459-18d17500-cc33-11ea-9082-6214bd7165ba.png)

P.S. there is no errors in console

**Comment by rozetko** [comment]
the problem is that Default datasource was used, related issue: https://github.com/CorpGlory/grafana-data-exporter-panel/issues/39
