### ISSUE TITLE
Error while adding export task Datasource is not set. If it`s Grafana-test-datasource then it`s not supported

### ISSUE THREAD

**Issue by skyfirst93** [CorpGlory/grafana-data-exporter-panel#70]
I am getting the Below mentioned error will trying to export data for a panel.
```
Error while adding export task
Datasource is not set. If it`s Grafana-test-datasource then it`s not supported
```

I have used grafana dashboard 8588 and add data exporter panel. 
I am using latest image of data exporter 
Grafana version : 7.3.1
panel version : 0.5.1 

Also, In one more setup when i click the export button nothing is happening. 

Please let me know if more info is required

**Comment by rozetko** [comment]
Hey @skyfirst93! It's a known problem, the progress can be tracked here: https://github.com/CorpGlory/grafana-data-exporter-panel/issues/69
